---
title: "HW6 Interactive Plots with plotly()"
author: "Q Liang"
date: "3/5/2024"
output:
  html_document: 
    toc: yes
    toc_depth: 4
    toc_float: yes
    fig_width: 6
    number_sections: yes
    toc_collapsed: yes
    code_folding: hide
    code_download: yes
    smooth_scroll: true
    theme: readable
    fig_height: 4
---

```{=html}
<style type="text/css">

div#TOC li {
    list-style:none;
    background-color:lightgray;
    background-image:none;
    background-repeat:none;
    background-position:0;
    font-family: Arial, Helvetica, sans-serif;
    color: #780c0c;
}

/* mouse over link */
div#TOC a:hover {
  color: red;
}

/* unvisited link */
div#TOC a:link {
  color: blue;
}



h1.title {
  font-size: 24px;
  color: Darkblue;
  text-align: center;
  font-family: Arial, Helvetica, sans-serif;
  font-variant-caps: normal;
}
h4.author { 
    font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  color: DarkRed;
  text-align: center;
}
h4.date { 
  font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  color: DarkBlue;
  text-align: center;
}
h1 {
    font-size: 24px;
    font-family: "Times New Roman", Times, serif;
    color: darkred;
    text-align: center;
}
h2 {
    font-size: 18px;
    font-family: "Times New Roman", Times, serif;
    color: navy;
    text-align: left;
}

h3 { 
    font-size: 15px;
    font-family: "Times New Roman", Times, serif;
    color: navy;
    text-align: left;
}

h4 { /* Header 4 - and the author and data headers use this too  */
    font-size: 18px;
    font-family: "Times New Roman", Times, serif;
    color: darkred;
    text-align: left;
}

/* unvisited link */
a:link {
  color: green;
}

/* visited link */
a:visited {
  color: green;
}

/* mouse over link */
a:hover {
  color: red;
}

/* selected link */
a:active {
  color: yellow;
}

</style>
```
```{r setup, include=FALSE}
# code chunk specifies whether the R code, warnings, and output 
# will be included in the output files.
options(repos = list(CRAN="http://cran.rstudio.com/"))
if (!require("tidyverse")) {
   install.packages("tidyverse")
   library(tidyverse)
}
if (!require("dplyr")) {
   install.packages("dplyr")
   library(dplyr)
}
if (!require("knitr")) {
   install.packages("knitr")
   library(knitr)
}
if (!require("cowplot")) {
   install.packages("cowplot")
   library(cowplot)
}
if (!require("latex2exp")) {
   install.packages("latex2exp")
   library(latex2exp)
}
if (!require("plotly")) {
   install.packages("plotly")
   library(plotly)
}
if (!require("gapminder")) {
   install.packages("gapminder")
   library(gapminder)
}
if (!require("png")) {
    install.packages("png")             # Install png package
    library("png")
}

              # Install RCurl package
    

if (!require("colourpicker")) {
    install.packages("colourpicker")              
    library("colourpicker")
}
if (!require("gifski")) {
    install.packages("gifski")              
    library("gifski")
}
if (!require("magick")) {
    install.packages("magick")              
    library("magick")
}
if (!require("grDevices")) {
    install.packages("grDevices")              
    library("grDevices")
}
### ggplot and extensions
if (!require("ggplot2")) {
    install.packages("ggplot2")              
    library("ggplot2")
}
if (!require("gganimate")) {
    install.packages("gganimate")              
    library("gganimate")
}
if (!require("ggridges")) {
    install.packages("ggridges")              
    library("ggridges")
}
if (!require("graphics")) {
    install.packages("graphics")              
    library("graphics")
}

knitr::opts_chunk$set(echo = TRUE,       
                      warning = FALSE,   
                      result = TRUE,   
                      message = FALSE,
                      comment = NA)
```

\

# Prepare a single data set

1.  Life expectancy and income for the year 2015. 

```{r, fig.align='center'}
#Read data.
data0 <- read.csv ("/Users/qianshengliang/Dropbox/STA553/Week 6/LifeExpIncom.csv",
                   header=TRUE,sep=",", colClasses=c("NULL", NA, NA,NA,NA,NA,NA))
#DT::datatable(data0, fillContainer = FALSE, options = list(pageLength = 10))
#2015data
year.id=which(data0$year=="2015")
data2015 = data0[year.id,]
#range(data2015$pop) #11000 - 1400000000
#range(data2015$income) #623 - 120000
#range(data2015$lifeExp,na.rm=TRUE) #49.6 -83.8
#work data
data1 <- data2015
data1$pop2 <- (log(data2015$pop)-9)
#range(data1$pop2) #0.3-12
#write.csv (data2015, "/Users/qianshengliang/Dropbox/STA553/Week 6/data2015.csv")
DT::datatable(data2015, fillContainer = FALSE, options = list(pageLength = 10))
```

# Make an interactive scatter plot 
To display the association between life expectancy and income for the year 2015.

```{r, fig.align='center'}
plot_ly(
  data = data1,
  x = ~income,  # Horizontal axis 
  y = ~lifeExp,   # Vertical axis 
  color = ~factor(country),  
  text = ~paste("<br>Country: ", country,
                "</br>Population: ", pop,
                "</br>Income: ", income,
                "</br>lifeExp: ", lifeExp),
  hoverinfo = "text",
  alpha  = 0.2,
  marker = list(size = ~(pop2), sizeref = 0.1, sizemode = 'area' ),
  type = "scatter",
  mode = "markers",
  ## graphic size
  width = 900,
  height = 700
) %>%
  layout(  
    ### Title 
    title =list(text = "Association between Income and Life Expectancy at 2015", 
                font = list(family = "Times New Roman",  # HTML font family  
                            size = 18,
                            color = "red")), 
    ### legend
    showlegend = FALSE,
    ## margin of the plot
    margin = list(
      b = 100,
      l = 100,
      t = 100,
      r = 50
    ),
    ## Background
    plot_bgcolor ='#f7f7f7', 
    ## Axes labels
    xaxis = list( 
      title=list(text = 'Income',
                 font = list(family = 'Arial')),
      zerolinecolor = 'black', 
      zerolinewidth = 2, 
      gridcolor = 'white'), 
    yaxis = list( 
      title=list(text = 'Life Exoetancy',
                 font = list(family = 'Arial')),
      zerolinecolor = 'purple', 
      zerolinewidth = 2, 
      gridcolor = 'white',
      range=c(40,90)),
    ## annotations
    annotations = list(  
      x = 0.8,   # between 0 and 1. 0 = left, 1 = right
      y = 42,   # between 0 and 1, 0 = bottom, 1 = top
      font = list(size = 12,
                  color = "darkred"),   
      text = "The point size is proportional to the population",   
      xref = "paper",  # "container" spans the entire `width` of the 
      #  lot. "paper" refers to the width of the 
      #  plotting area only. yref = "paper",  
      #  same as xref.
      xanchor = "center", #  horizontal alignment with respect to its x position
      yanchor = "bottom", #  similar to xanchor  
      showarrow = FALSE)
  )
```

The graph shows the relation between income and life expectancy of 193 countries/regions in 2015. The size of the points is proportioned to population and colors represent different contries. 